#!/bin/sh
# build-all-in-one.sh — regenerate csharp/supabase-all-in-one.sql from
# csharp/migrations.order. Idempotent and re-runnable (the output file is
# truncated and rebuilt on every run).
#
# Usage (from anywhere; paths resolve relative to the repo root):
#   sh csharp/build-all-in-one.sh
#
# DO NOT hand-edit csharp/supabase-all-in-one.sql — edit the migrations or
# migrations.order and re-run this script.

set -eu

# Resolve the script's own directory (csharp/) and the repo root, so the
# script works regardless of the current working directory.
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)

MANIFEST="$SCRIPT_DIR/migrations.order"
OUTPUT="$SCRIPT_DIR/supabase-all-in-one.sql"

if [ ! -f "$MANIFEST" ]; then
  printf 'ERROR: manifest not found: %s\n' "$MANIFEST" >&2
  exit 1
fi

# Write the header (truncates any previous output).
{
  printf -- '-- GENERATED by build-all-in-one.sh from migrations.order — DO NOT EDIT BY HAND.\n'
  printf -- '-- Regenerate with: sh csharp/build-all-in-one.sh\n'
  printf -- '-- Single source of truth: csharp/migrations.order\n'
} > "$OUTPUT"

count=0
while IFS= read -r line || [ -n "$line" ]; do
  # Skip blank lines and comments.
  case "$line" in
    ''|\#*) continue ;;
  esac

  file="$REPO_ROOT/$line"
  if [ ! -f "$file" ]; then
    printf 'ERROR: migration listed in manifest is missing: %s\n' "$file" >&2
    exit 1
  fi

  {
    printf -- '\n-- ===== %s =====\n\n' "$line"
    cat "$file"
    printf -- '\n'
  } >> "$OUTPUT"

  count=$((count + 1))
done < "$MANIFEST"

printf 'Wrote %s (%d migrations).\n' "$OUTPUT" "$count"
